### ISSUE TITLE
[작업] 메인, 로그인, 회원가입 인터페이스 마무리

### ISSUE THREAD

**Issue by JSukhen2** [Vactor0911/wanna-trip#24]
기능
메인, 로그인, 회원가입 인터페이스에 부족한 기능 및 디자인 마무리

해야할 일

- [x] 메인 인터페이스 완료
- [x] 로그인 인터페이스 완료
- [x] 회원가입 인터페이스 완료
- [x] 전체 완료

**Comment by L-Hits** [comment]
로그인 인터페이스 수정 부탁드립니다.
dev 합쳐놨어요.
